version: "3.7"

services:
    master:
        image: alltrim/postgres:15-1C
        networks:
            - net
        ports:
            - 5432:5432
        volumes:
            - data:/var/lib/pgpro/1c-15/data

networks:
    net:


volumes:
    data:
